name: Build & Tests

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  ZEROCOPY_MSRV: 1.61.0
  ZEROCOPY_CURRENT_STABLE: 1.64.0
  ZEROCOPY_CURRENT_NIGHTLY: nightly-2022-09-26

jobs:
  compute:
    runs-on: ubuntu-latest
    outputs:
      ZEROCOPY_MSRV: ${{ env.ZEROCOPY_MSRV }}
      ZEROCOPY_CURRENT_STABLE: ${{ env.ZEROCOPY_CURRENT_STABLE }}
      ZEROCOPY_CURRENT_NIGHTLY: ${{ env.ZEROCOPY_CURRENT_NIGHTLY }}
    steps:
      - name: Compute outputs
        run: |
          echo "ZEROCOPY_MSRV=${{ env.ZEROCOPY_MSRV }}" >> $GITHUB_OUTPUT
          echo "ZEROCOPY_CURRENT_STABLE=${{ env.ZEROCOPY_CURRENT_STABLE }}" >> $GITHUB_OUTPUT
          echo "ZEROCOPY_CURRENT_NIGHTLY=${{ env.ZEROCOPY_CURRENT_NIGHTLY }}" >> $GITHUB_OUTPUT

  build_test:
    runs-on: ubuntu-latest
    needs: compute
    strategy:
      matrix:
        channel: ["${{ needs.compute.outputs.ZEROCOPY_MSRV }}", "${{ needs.compute.outputs.ZEROCOPY_CURRENT_STABLE }}", "${{ needs.compute.outputs.ZEROCOPY_CURRENT_NIGHTLY }}"]
        target: ["i686-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "arm-unknown-linux-gnueabi", "aarch64-unknown-linux-gnu", "powerpc-unknown-linux-gnu", "powerpc64-unknown-linux-gnu", "wasm32-wasi"]
        features: ["" , "alloc,simd", "alloc,simd,simd-nightly"]
        exclude:
          - channel: ${{ needs.compute.outputs.ZEROCOPY_MSRV }}
            features: "alloc,simd,simd-nightly"
          - channel: ${{ needs.compute.outputs.ZEROCOPY_CURRENT_STABLE }}
            features: "alloc,simd,simd-nightly"
    steps:
      - name: Run matrix for ${{ matrix.channel }}-${{ matrix.target }}-${{ matrix.features }}"
        run: |
          echo "Channel: ${{ matrix.channel }}"
          echo "Target: ${{ matrix.target }}"
          echo "Features: ${{ matrix.features }}"
